export const APP_WRITE_ID = 'crm-system-nuxt-record123'
export const DB_ID = '68acc5b50032ea8842e7'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
